export default {
  daily: [
    { category: "Work", hours: 5, lastWeek: 7, color: "#FF8B64", icon: "work" },
    { category: "Play", hours: 1, lastWeek: 2, color: "#55C2E6", icon: "play" },
    {
      category: "Study",
      hours: 0,
      lastWeek: 1,
      color: "#FF5E7D",
      icon: "study",
    },
    {
      category: "Exercise",
      hours: 1,
      lastWeek: 1,
      color: "#4BCF82",
      icon: "exercise",
    },
    {
      category: "Social",
      hours: 1,
      lastWeek: 3,
      color: "#7335D2",
      icon: "social",
    },
    {
      category: "Self Care",
      hours: 0,
      lastWeek: 1,
      color: "#F1C75B",
      icon: "selfCare",
    },
  ],
  weekly: [
    {
      category: "Work",
      hours: 32,
      lastWeek: 36,
      color: "#FF8B64",
      icon: "work",
    },
    {
      category: "Play",
      hours: 10,
      lastWeek: 8,
      color: "#55C2E6",
      icon: "play",
    },
    {
      category: "Study",
      hours: 4,
      lastWeek: 7,
      color: "#FF5E7D",
      icon: "study",
    },
    {
      category: "Exercise",
      hours: 4,
      lastWeek: 5,
      color: "#4BCF82",
      icon: "exercise",
    },
    {
      category: "Social",
      hours: 5,
      lastWeek: 10,
      color: "#7335D2",
      icon: "social",
    },
    {
      category: "Self Care",
      hours: 2,
      lastWeek: 2,
      color: "#F1C75B",
      icon: "selfCare",
    },
  ],
  monthly: [
    {
      category: "Work",
      hours: 103,
      lastWeek: 128,
      color: "#FF8B64",
      icon: "work",
    },
    {
      category: "Play",
      hours: 23,
      lastWeek: 29,
      color: "#55C2E6",
      icon: "play",
    },
    {
      category: "Study",
      hours: 13,
      lastWeek: 19,
      color: "#FF5E7D",
      icon: "study",
    },
    {
      category: "Exercise",
      hours: 11,
      lastWeek: 18,
      color: "#4BCF82",
      icon: "exercise",
    },
    {
      category: "Social",
      hours: 21,
      lastWeek: 23,
      color: "#7335D2",
      icon: "social",
    },
    {
      category: "Self Care",
      hours: 7,
      lastWeek: 11,
      color: "#F1C75B",
      icon: "selfCare",
    },
  ],
};
